[platformio]
default_envs = nodemcuv2

[env:nodemcuv2]
platform = espressif8266@4.2.1
board = nodemcuv2
framework = arduino
monitor_speed = 115200
board_build.filesystem = littlefs
lib_deps =
  bblanchon/ArduinoJson @ ^7.4.2
build_flags =
  -Wall
  -Wextra

[env:native]
platform = native
test_framework = unity
test_filter = test_core
build_flags =
  -std=gnu++17
  -Wall
  -Wextra

